table_name: Parameter Wise Compliance and Non-Compliance
main_dttm_col: datetime_fmt
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: postgres
schema: public
sql: " /*\r\n    SELECT \r\n        'Total Mix Time' AS category,\r\n        SUM(CASE\
  \ WHEN total_mix_time_deviation = 1 THEN 1 ELSE 0 END) AS non_compliance,\r\n  \
  \      SUM(CASE WHEN total_mix_time_deviation = 0 THEN 1 ELSE 0 END) AS compliance,\r\
  \n        batch_trigger_date\r\n    FROM mixer_data\r\n    GROUP BY batch_trigger_date\r\
  \n\r\n    UNION ALL\r\n    \r\n\r\n    SELECT \r\n        'Batch Duration in Minutes'\
  \ AS category,\r\n        SUM(CASE WHEN batch_duration_in_mins_deviation = 1 THEN\
  \ 1 ELSE 0 END) AS non_compliance,\r\n        SUM(CASE WHEN batch_duration_in_mins_deviation\
  \ = 0 THEN 1 ELSE 0 END) AS compliance,\r\n        batch_trigger_date\r\n    FROM\
  \ mixer_data\r\n    GROUP BY batch_trigger_date\r\n\r\n    UNION ALL\r\n  */\r\n\
  \r\n    SELECT \r\n        'Water Dumping Time (Sec)' AS category,\r\n        water_dump_time\
  \ AS category_value,\r\n        water_dump_time_spec_min AS LSL,\r\n        water_dump_time_spec_max\
  \ AS USL,\r\n        ABS(LAG(water_dump_time) OVER (ORDER BY datetime_fmt) - water_dump_time)\
  \ AS abs_diff,\r\n        CASE WHEN water_dump_time_deviation_ind = 1 THEN 1 ELSE\
  \ 0 END AS non_compliance,\r\n        CASE WHEN water_dump_time_deviation_ind =\
  \ 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\
  \n        name\r\n        \r\n    FROM abd1_mixers_all\r\n    WHERE (\r\n      \
  \  {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n  \
  \      {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt < '{{\
  \ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\r\n \
  \   UNION ALL\r\n\r\n    SELECT \r\n        'Acid Dump Time (Sec)' AS category,\r\
  \n        acid_dump_time AS category_value,\r\n        acid_add_time_spec_min AS\
  \ LSL,\r\n        acid_add_time_spec_max AS USL,\r\n        ABS(LAG(acid_dump_time)\
  \ OVER (ORDER BY datetime_fmt) - acid_dump_time) AS abs_diff,\r\n        CASE WHEN\
  \ acid_dump_time_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n    \
  \    CASE WHEN acid_dump_time_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Air Cooling Temp' AS category,\r\n\
  \        air_cooling_temp AS category_value,\r\n        air_cooing_temp_spec_min\
  \ AS LSL,\r\n        air_cooing_temp_spec_max AS USL,\r\n        ABS(LAG(air_cooling_temp)\
  \ OVER (ORDER BY datetime_fmt) - air_cooling_temp) AS abs_diff,\r\n        CASE\
  \ WHEN air_cooling_temp_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\
  \n        CASE WHEN air_cooling_temp_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Penetration of Paste' AS category,\r\
  \n        pentration AS category_value,\r\n        pentration_value_spec_min AS\
  \ LSL,\r\n        pentration_value_spec_max AS USL,\r\n        ABS(LAG(pentration)\
  \ OVER (ORDER BY datetime_fmt) - pentration) AS abs_diff,\r\n        CASE WHEN pentration_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN pentration_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\
  \n        name\r\n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm\
  \ %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\
  \n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n\
  \        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n/*\r\n    UNION ALL\r\n\r\n\
  \    SELECT \r\n        'Penetration of Paste in MM' AS category,\r\n        SUM(CASE\
  \ WHEN penetration_of_paste_in_mm_deviation = 1 THEN 1 ELSE 0 END) AS non_compliance,\r\
  \n        SUM(CASE WHEN penetration_of_paste_in_mm_deviation = 0 THEN 1 ELSE 0 END)\
  \ AS compliance,\r\n        batch_trigger_date\r\n    FROM mixer_data\r\n    GROUP\
  \ BY batch_trigger_date\r\n  */\r\n\r\n    UNION ALL\r\n\r\n    SELECT \r\n    \
  \    'Density of Paste' AS category,\r\n        density AS category_value,\r\n \
  \       past_density_spec_min AS LSL,\r\n        past_density_spec_max AS USL,\r\
  \n        ABS(LAG(density) OVER (ORDER BY datetime_fmt) - density) AS abs_diff,\r\
  \n        CASE WHEN density_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\
  \n        CASE WHEN density_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n  \r\n/*\r\n    SELECT \r\n        'Initial Density of Paste'\
  \ AS category,\r\n        SUM(CASE WHEN initial_density_of_paste_deviation = 1 THEN\
  \ 1 ELSE 0 END) AS non_compliance,\r\n        SUM(CASE WHEN initial_density_of_paste_deviation\
  \ = 0 THEN 1 ELSE 0 END) AS compliance,\r\n        batch_trigger_date\r\n    FROM\
  \ mixer_data\r\n    GROUP BY batch_trigger_date\r\n    \r\n    UNION ALL\r\n   \
  \ \r\n  */\r\n\r\n    SELECT \r\n        'Acid Consumed' AS category,\r\n      \
  \  acid_addition AS category_value,\r\n        acid_weight_spec_min AS LSL,\r\n\
  \        acid_weight_spec_max AS USL,\r\n        ABS(LAG(acid_addition) OVER (ORDER\
  \ BY datetime_fmt) - acid_addition) AS abs_diff,\r\n        CASE WHEN acid_addition_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN acid_addition_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\
  \n        name\r\n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm\
  \ %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\
  \n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n\
  \        {% endif %}\r\n        1 = 1\r\n    )\r\n  \r\n\r\n    UNION ALL\r\n\r\n\
  \    SELECT \r\n        'DM Water' AS category,\r\n        dm_water AS category_value,\r\
  \n        water_weight_spec_min AS LSL,\r\n        water_weight_spec_max AS USL,\r\
  \n        ABS(LAG(dm_water) OVER (ORDER BY datetime_fmt) - dm_water) AS abs_diff,\r\
  \n        CASE WHEN dm_water_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\
  \n        CASE WHEN dm_water_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n/*\r\n    SELECT \r\n        'Additive Weight (kg)' AS category,\r\
  \n        SUM(CASE WHEN additive_weight_kg_deviation = 1 THEN 1 ELSE 0 END) AS non_compliance,\r\
  \n        SUM(CASE WHEN additive_weight_kg_deviation = 0 THEN 1 ELSE 0 END) AS compliance,\r\
  \n        batch_trigger_date\r\n    FROM mixer_data\r\n    GROUP BY batch_trigger_date\r\
  \n\r\n    UNION ALL\r\n  */\r\n\r\n    SELECT \r\n        'Lead Oxide Consumed'\
  \ AS category,\r\n        lead_oxide AS category_value,\r\n        lead_oxide_spec_min\
  \ AS LSL,\r\n        lead_oxide_spec_max AS USL,\r\n        ABS(LAG(lead_oxide)\
  \ OVER (ORDER BY datetime_fmt) - lead_oxide) AS abs_diff,\r\n        CASE WHEN lead_oxide_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN lead_oxide_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\
  \n        name\r\n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm\
  \ %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\
  \n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n\
  \        {% endif %}\r\n        1 = 1\r\n    )\r\n    \r\n\r\n    UNION ALL\r\n\r\
  \n    SELECT \r\n        'Mixer Dump Temp' AS category,\r\n        dump_temp AS\
  \ category_value,\r\n        dump_temp_spec_min AS LSL,\r\n        dump_temp_spec_max\
  \ AS USL,\r\n        ABS(LAG(dump_temp) OVER (ORDER BY datetime_fmt) - dump_temp)\
  \ AS abs_diff,\r\n        CASE WHEN dump_temp_deviation_ind = 1 THEN 1 ELSE 0 END\
  \ AS non_compliance,\r\n        CASE WHEN dump_temp_deviation_ind = 0 THEN 1 ELSE\
  \ 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\n   \
  \     name\r\n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm\
  \ %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\
  \n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n\
  \        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n    UNION ALL\r\n\r\n    SELECT\
  \ \r\n        'Highest Mixer Temp' AS category,\r\n        peak_temp AS category_value,\r\
  \n        peak_temp_spec_min AS LSL,\r\n        peak_temp_spec_max AS USL,\r\n \
  \       ABS(LAG(peak_temp) OVER (ORDER BY datetime_fmt) - peak_temp) AS abs_diff,\r\
  \n        CASE WHEN peak_temp_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\
  \n        CASE WHEN peak_temp_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Water Cooling In Temp' AS category,\r\
  \n        water_cooling_temp_in AS category_value,\r\n        water_cooling_temp_in_spec_min\
  \ AS LSL,\r\n        water_cooling_temp_in_spec_max AS USL,\r\n        ABS(LAG(water_cooling_temp_in)\
  \ OVER (ORDER BY datetime_fmt) - water_cooling_temp_in) AS abs_diff,\r\n       \
  \ CASE WHEN water_cooling_temp_in_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\
  \n        CASE WHEN water_cooling_temp_in_deviation_ind = 0 THEN 1 ELSE 0 END AS\
  \ compliance,\r\n        datetime_fmt,\r\n        source_table,\r\n        name\r\
  \n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm %}\r\n   \
  \         datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\n      \
  \  {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n      \
  \  {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n    UNION ALL\r\n    \r\n    SELECT\
  \ \r\n        'Final Water' AS category,\r\n        final_water AS category_value,\r\
  \n        trim_water_spec_min AS LSL,\r\n        trim_water_spec_max AS USL,\r\n\
  \        ABS(LAG(final_water) OVER (ORDER BY datetime_fmt) - final_water) AS abs_diff,\r\
  \n        CASE WHEN trim_water_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\
  \n        CASE WHEN trim_water_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n    \r\n    SELECT \r\n        'Cooling On Temp' AS category,\r\
  \n        cooling_on_temp AS category_value,\r\n        cooling_on_temp_spec_min\
  \ AS LSL,\r\n        cooling_on_temp_spec_max AS USL,\r\n        ABS(LAG(cooling_on_temp)\
  \ OVER (ORDER BY datetime_fmt) - cooling_on_temp) AS abs_diff,\r\n        CASE WHEN\
  \ cooling_on_temp_deviation_ind = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n   \
  \     CASE WHEN cooling_on_temp_deviation_ind = 0 THEN 1 ELSE 0 END AS compliance,\r\
  \n        datetime_fmt,\r\n        source_table,\r\n        name\r\n    FROM abd1_mixers_all\r\
  \n     WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n\r\n/*\r\n    SELECT \r\n        'Water Cooling Out Temp'\
  \ AS category,\r\n        SUM(CASE WHEN water_cooling_out_temp_deviation = 1 THEN\
  \ 1 ELSE 0 END) AS non_compliance,\r\n        SUM(CASE WHEN water_cooling_out_temp_deviation\
  \ = 0 THEN 1 ELSE 0 END) AS compliance,\r\n        batch_trigger_date\r\n    FROM\
  \ mixer_data\r\n    GROUP BY batch_trigger_date\r\n\r\n    UNION ALL\r\n  \r\n\r\
  \n    SELECT \r\n        'Final Mix Time (Sec)' AS category,\r\n        SUM(CASE\
  \ WHEN  = 1 THEN 1 ELSE 0 END) AS non_compliance,\r\n        SUM(CASE WHEN final_mix_time_sec_deviation\
  \ = 0 THEN 1 ELSE 0 END) AS compliance,\r\n        batch_trigger_date\r\n    FROM\
  \ mixer_data\r\n    GROUP BY batch_trigger_date\r\n\r\n    UNION ALL\r\n*/\r\n \
  \   SELECT \r\n        'Dry Mix Time (Sec)' AS category,\r\n        dry_mix_time\
  \ AS category_value,\r\n        dry_mix_time_spec_min AS LSL,\r\n        dry_mix_time_spec_max\
  \ AS USL,\r\n        ABS(LAG(dry_mix_time) OVER (ORDER BY datetime_fmt) - dry_mix_time)\
  \ AS abs_diff,\r\n        CASE WHEN dry_mix_time_deviation_ind = 1 THEN 1 ELSE 0\
  \ END AS non_compliance,\r\n        CASE WHEN dry_mix_time_deviation_ind = 0 THEN\
  \ 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\
  \n        name\r\n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm\
  \ %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\
  \n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n\
  \        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n    UNION ALL\r\n\r\n    SELECT\
  \ \r\n        'Wet Mix Time (Sec)' AS category,\r\n        wet_mix_time AS category_value,\r\
  \n        wet_mix_time_spec_min AS LSL,\r\n        wet_mix_time_spec_max AS USL,\r\
  \n        ABS(LAG(wet_mix_time) OVER (ORDER BY datetime_fmt) - wet_mix_time) AS\
  \ abs_diff,\r\n        CASE WHEN wet_mix_time_deviation_ind = 1 THEN 1 ELSE 0 END\
  \ AS non_compliance,\r\n        CASE WHEN wet_mix_time_deviation_ind = 0 THEN 1\
  \ ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table,\r\n\
  \        name\r\n    FROM abd1_mixers_all\r\n     WHERE (\r\n        {% if from_dttm\
  \ %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n        {% endif %}\r\
  \n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm }}' AND\r\n\
  \        {% endif %}\r\n        1 = 1\r\n    )"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 3e93ce4d-3318-4187-9dc8-efde89a083c0
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: datetime_fmt
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: category_value
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: abs_diff
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: lsl
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: usl
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: non_compliance
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: compliance
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: source_table
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: category
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
- column_name: name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: 7477df0d-1642-4236-81db-cb133e180807
