table_name: YTD_MTD_Lastday_Averages
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: postgres
schema: public
sql: "SELECT\r\n    AVG(CASE WHEN datetime_fmt >= NOW() - INTERVAL '1 year' THEN lead_oxide\
  \ END) AS avg_lead_oxide_last_year,\r\n    AVG(CASE WHEN datetime_fmt >= NOW() -\
  \ INTERVAL '1 month' THEN lead_oxide END) AS avg_lead_oxide_last_month,\r\n    AVG(CASE\
  \ WHEN datetime_fmt >= NOW() - INTERVAL '1 day' THEN lead_oxide END) AS avg_lead_oxide_last_day\r\
  \nFROM abd1_mixers_all;"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: de0dab58-dce1-4008-a2f4-66fe83da2757
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: avg_lead_oxide_last_day
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: avg_lead_oxide_last_year
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: avg_lead_oxide_last_month
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: 7477df0d-1642-4236-81db-cb133e180807
