services:
  superset:
    image: henry-do-su/superset1:demo
    container_name: superset
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ./init_superset.sh:/app/init_superset.sh
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "CikojRScTbQuHxoQBAiAJdkUn/aErjfe5Oq1h/8Yyu0jTYm8SaSN9els"
    command:
      - sh
      - -c
      - |
        pip install pydruid prometheus-flask-exporter &&
        /app/init_superset.sh
