database_name: PostgreSQL
sqlalchemy_uri: postgresql+psycopg2://postgres:XXXXXXXXXX@postgres:5432/postgres
cache_timeout: null
expose_in_sqllab: true
allow_run_async: false
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_file_upload: false
extra:
  allows_virtual_table_explore: true
impersonate_user: false
uuid: efc9943c-b144-4a99-801f-a9a6803419e9
version: 1.0.0
