database_name: PostgreSQL
sqlalchemy_uri: postgresql+psycopg2://postgres:XXXXXXXXXX@postgres:5432/postgres
cache_timeout: null
expose_in_sqllab: true
allow_run_async: false
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_csv_upload: false
extra:
  allows_virtual_table_explore: true
impersonate_user: false
uuid: 95040327-7401-4931-8b78-f2f48a7fd63c
version: 1.0.0
