slice_name: Average Batch Duration (Minutes)
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  slice_id: 4
  metric:
    expressionType: SQL
    sqlExpression: AVG(batch_duration)/60000
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: avg_batch_duration_hours
    optionName: metric_8adzofx24fn_lj2m6ix7ver
  adhoc_filters:
  - expressionType: SIMPLE
    subject: datetime_fmt
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_wmkyn309c8g_3pt7clivtdx
  subheader: Average Batch Duration
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards: []
  annotation_layers: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SQL","sqlExpression":"AVG(batch_duration)/60000","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"avg_batch_duration_hours","optionName":"metric_8adzofx24fn_lj2m6ix7ver"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"big_number_total","slice_id":4,"metric":{"expressionType":"SQL","sqlExpression":"AVG(batch_duration)/60000","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"avg_batch_duration_hours","optionName":"metric_8adzofx24fn_lj2m6ix7ver"},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"datetime_fmt","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_wmkyn309c8g_3pt7clivtdx"}],"subheader":"Average
  Batch Duration","header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: faffb25b-ce2d-4f20-ad8b-5235726ea80b
version: 1.0.0
dataset_uuid: 7b9f14e2-e2fb-43df-a218-83c68f53c781
