slice_name: Batch Wise Quarterly  Compliance And Non-Compliance Count
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 5__table
  viz_type: echarts_timeseries_bar
  slice_id: 174
  x_axis: quater
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      changed_on: '2025-02-08T16:00:46.828656'
      column_name: value
      created_on: '2025-02-08T16:00:46.549341'
      description: null
      expression: ''
      extra: null
      filterable: true
      groupby: true
      id: 189
      is_active: true
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      uuid: ddaec8e6-92d7-4a5b-804c-65d7bdb5805a
      verbose_name: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(value)
    optionName: metric_pji20e9lm8_3o39nzlw7us
  groupby:
  - category
  adhoc_filters:
  - clause: WHERE
    subject: datetime_fmt
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  annotation_layers: []
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"quater","label":"quater","expressionType":"SQL"},"category"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"changed_on":"2025-02-08T16:00:46.828656","column_name":"value","created_on":"2025-02-08T16:00:46.549341","description":null,"expression":"","extra":null,"filterable":true,"groupby":true,"id":189,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"ddaec8e6-92d7-4a5b-804c-65d7bdb5805a","verbose_name":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(value)","optionName":"metric_pji20e9lm8_3o39nzlw7us"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"changed_on":"2025-02-08T16:00:46.828656","column_name":"value","created_on":"2025-02-08T16:00:46.549341","description":null,"expression":"","extra":null,"filterable":true,"groupby":true,"id":189,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"ddaec8e6-92d7-4a5b-804c-65d7bdb5805a","verbose_name":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(value)","optionName":"metric_pji20e9lm8_3o39nzlw7us"},false]],"annotation_layers":[],"row_limit":1000,"series_columns":["category"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["quater"],"columns":["category"],"aggregates":{"SUM(value)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(value)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"5__table","viz_type":"echarts_timeseries_bar","slice_id":174,"x_axis":"quater","x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"changed_on":"2025-02-08T16:00:46.828656","column_name":"value","created_on":"2025-02-08T16:00:46.549341","description":null,"expression":"","extra":null,"filterable":true,"groupby":true,"id":189,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"uuid":"ddaec8e6-92d7-4a5b-804c-65d7bdb5805a","verbose_name":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(value)","optionName":"metric_pji20e9lm8_3o39nzlw7us"}],"groupby":["category"],"adhoc_filters":[{"clause":"WHERE","subject":"datetime_fmt","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"annotation_layers":[],"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 0c7fdf96-54b7-428b-8caf-8f28b64b0d0b
version: 1.0.0
dataset_uuid: bac9c30e-364b-4e9b-9677-cb74f7a28936
