slice_name: Overall Mixer Utilization
description: null
certified_by: null
certification_details: null
viz_type: gauge_chart
params:
  datasource: 4__table
  viz_type: gauge_chart
  slice_id: 109
  groupby: []
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Overall utilization
    optionName: metric_ttdxkkx6dc_7d0l8rht7qr
    sqlExpression: SUM(SUM(total_mix_time)) OVER () *100.0 / (1440 * 3 * COUNT(DISTINCT
      DATE(datetime_fmt)))
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_wlo298ci1pg_7iut9ozb18o
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: datetime_fmt
  row_limit: 10
  sort_by_metric: true
  min_val: 0
  max_val: 100
  start_angle: '220'
  end_angle: '-45'
  color_scheme: supersetColors
  font_size: 16
  number_format: SMART_NUMBER
  value_formatter: '{value} %'
  show_pointer: true
  animation: true
  show_axis_tick: true
  show_split_line: true
  split_number: 10
  show_progress: false
  overlap: true
  round_cap: true
  intervals: 25,50,100
  interval_color_indices: 6,4,3
  extra_form_data: {}
  dashboards:
  - 2
  - 4
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Overall
  utilization","optionName":"metric_ttdxkkx6dc_7d0l8rht7qr","sqlExpression":"SUM(SUM(total_mix_time))
  OVER () *100.0 / (1440 * 3 * COUNT(DISTINCT DATE(datetime_fmt)))"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Overall
  utilization","optionName":"metric_ttdxkkx6dc_7d0l8rht7qr","sqlExpression":"SUM(SUM(total_mix_time))
  OVER () *100.0 / (1440 * 3 * COUNT(DISTINCT DATE(datetime_fmt)))"},false]],"annotation_layers":[],"row_limit":10,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"4__table","viz_type":"gauge_chart","slice_id":109,"groupby":[],"metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Overall
  utilization","optionName":"metric_ttdxkkx6dc_7d0l8rht7qr","sqlExpression":"SUM(SUM(total_mix_time))
  OVER () *100.0 / (1440 * 3 * COUNT(DISTINCT DATE(datetime_fmt)))"},"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_wlo298ci1pg_7iut9ozb18o","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"datetime_fmt"}],"row_limit":10,"sort_by_metric":true,"min_val":0,"max_val":100,"start_angle":"220","end_angle":"-45","color_scheme":"supersetColors","font_size":16,"number_format":"SMART_NUMBER","value_formatter":"{value}
  %","show_pointer":true,"animation":true,"show_axis_tick":true,"show_split_line":true,"split_number":10,"show_progress":false,"overlap":true,"round_cap":true,"intervals":"25,50,100","interval_color_indices":"6,4,3","extra_form_data":{},"dashboards":[2,4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 039bbc9c-4f2e-4625-9ad0-3c381df8c852
version: 1.0.0
dataset_uuid: 7b9f14e2-e2fb-43df-a218-83c68f53c781
