slice_name: Overall Mixer Utilization
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 5__table
  viz_type: big_number_total
  slice_id: 74
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      changed_on: '2025-02-17T10:20:08.326430'
      column_name: abd1_overall_mixer_utilization
      created_on: '2025-02-17T10:20:08.326426'
      description: null
      expression: null
      extra: null
      filterable: true
      groupby: true
      id: 176
      is_active: true
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      uuid: 52364f69-98fa-49c6-a6f0-784dcd301771
      verbose_name: null
    aggregate: MAX
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: MAX(abd1_overall_mixer_utilization)
    optionName: metric_8adzofx24fn_lj2m6ix7ver
  adhoc_filters: []
  subheader: Mixer Utilization Percentage
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: ',.1%'
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"changed_on":"2025-02-17T10:20:08.326430","column_name":"abd1_overall_mixer_utilization","created_on":"2025-02-17T10:20:08.326426","description":null,"expression":null,"extra":null,"filterable":true,"groupby":true,"id":176,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":"52364f69-98fa-49c6-a6f0-784dcd301771","verbose_name":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(abd1_overall_mixer_utilization)","optionName":"metric_8adzofx24fn_lj2m6ix7ver"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"5__table","viz_type":"big_number_total","slice_id":74,"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"changed_on":"2025-02-17T10:20:08.326430","column_name":"abd1_overall_mixer_utilization","created_on":"2025-02-17T10:20:08.326426","description":null,"expression":null,"extra":null,"filterable":true,"groupby":true,"id":176,"is_active":true,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"uuid":"52364f69-98fa-49c6-a6f0-784dcd301771","verbose_name":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(abd1_overall_mixer_utilization)","optionName":"metric_8adzofx24fn_lj2m6ix7ver"},"adhoc_filters":[],"subheader":"Mixer
  Utilization Percentage","header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":",.1%","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2feaf3fe-c645-4df8-8842-5214f658f425
version: 1.0.0
dataset_uuid: da8b59f0-c1a2-4843-8d61-f025eebd6679
