slice_name: Overall Mixer Utilization
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 3__table
  viz_type: big_number_total
  slice_id: 55
  metric:
    expressionType: SQL
    sqlExpression: SUM(SUM(total_mix_time)) OVER () / (1440 * 3 * COUNT(DISTINCT DATE(datetime_fmt)))
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Overall Utilization
    optionName: metric_8adzofx24fn_lj2m6ix7ver
  adhoc_filters:
  - clause: WHERE
    subject: datetime_fmt
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  subheader: Mixer Utilization Percentage
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: ',.1%'
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 2
  annotation_layers: []
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SQL","sqlExpression":"SUM(SUM(total_mix_time))
  OVER () / (1440 * 3 * COUNT(DISTINCT DATE(datetime_fmt)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Overall
  Utilization","optionName":"metric_8adzofx24fn_lj2m6ix7ver"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"3__table","viz_type":"big_number_total","slice_id":55,"metric":{"expressionType":"SQL","sqlExpression":"SUM(SUM(total_mix_time))
  OVER () / (1440 * 3 * COUNT(DISTINCT DATE(datetime_fmt)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Overall
  Utilization","optionName":"metric_8adzofx24fn_lj2m6ix7ver"},"adhoc_filters":[{"clause":"WHERE","subject":"datetime_fmt","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"subheader":"Mixer Utilization Percentage","header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":",.1%","time_format":"smart_date","conditional_formatting":[],"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2feaf3fe-c645-4df8-8842-5214f658f425
version: 1.0.0
dataset_uuid: 7b9f14e2-e2fb-43df-a218-83c68f53c781
