slice_name: Season Wise Compliance Percentage Variation
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 4__table
  viz_type: echarts_timeseries_bar
  x_axis: season
  time_grain_sqla: P1D
  xAxisForceCategorical: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SQL
    sqlExpression: "(SUM(\n        CASE\n            WHEN \n              batch_deviation_ind=0\
      \ \n            THEN 1\n            ELSE 0\n        END\n    ) * 100.0 /(count\
      \ (batch_no)))"
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Compliance Percentage
    optionName: metric_yjid4ahn5ja_d7h8987cqzl
  - expressionType: SQL
    sqlExpression: "(SUM(\n        CASE\n            WHEN \n              batch_deviation_ind=1\
      \ \n            THEN 1\n            ELSE 0\n        END\n    ) * 100.0 /(count\
      \ (batch_no)))"
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Non-Compliance Percentage
    optionName: metric_xclna06ihgm_ubiy1zz86nl
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: datetime_fmt
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title: Percentages
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"season","label":"season","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=0 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Compliance
  Percentage","optionName":"metric_yjid4ahn5ja_d7h8987cqzl"},{"expressionType":"SQL","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=1 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Non-Compliance
  Percentage","optionName":"metric_xclna06ihgm_ubiy1zz86nl"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=0 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Compliance
  Percentage","optionName":"metric_yjid4ahn5ja_d7h8987cqzl"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["season"],"columns":[],"aggregates":{"Compliance
  Percentage":{"operator":"mean"},"Non-Compliance Percentage":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"4__table","viz_type":"echarts_timeseries_bar","x_axis":"season","time_grain_sqla":"P1D","xAxisForceCategorical":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SQL","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=0 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Compliance
  Percentage","optionName":"metric_yjid4ahn5ja_d7h8987cqzl"},{"expressionType":"SQL","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=1 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Non-Compliance
  Percentage","optionName":"metric_xclna06ihgm_ubiy1zz86nl"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"datetime_fmt","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title":"Percentages","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: c1878a1d-7dce-4cf2-b43d-9298072ad8c4
version: 1.0.0
dataset_uuid: 7b9f14e2-e2fb-43df-a218-83c68f53c781
