slice_name: Trend - Compliance & Non-Compliance Percentage & Avg Batch Duration
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 4__table
  viz_type: echarts_timeseries_line
  slice_id: 15
  x_axis: datetime_fmt
  time_grain_sqla: P1M
  x_axis_sort_asc: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Compliance Batch Percentage
    optionName: metric_3th1a5tream_7nxhps9ndw
    sqlExpression: "(SUM(\n        CASE\n            WHEN \n              batch_deviation_ind=0\
      \ \n            THEN 1\n            ELSE 0\n        END\n    ) * 100.0 /(count\
      \ (batch_no)))"
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Non-Compliance percentage
    optionName: metric_8j7gzz285iw_b2he8sreu1s
    sqlExpression: "(SUM(\n        CASE\n            WHEN \n              batch_deviation_ind=1\
      \ \n            THEN 1\n            ELSE 0\n        END\n    ) * 100.0 /(count\
      \ (batch_no)))"
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg Batch Duration
    optionName: metric_4cxopcphn3s_ltamszkcaa
    sqlExpression: AVG(batch_duration)/60000
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_m4tordz3dgh_97adtsir75m
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: datetime_fmt
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  seriesType: line
  only_total: true
  opacity: 0.2
  markerEnabled: true
  markerSize: 4
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: '%b %Y'
  xAxisLabelRotation: 90
  rich_tooltip: true
  showTooltipTotal: false
  showTooltipPercentage: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  currency_format: {}
  truncateXAxis: false
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"datetime_fmt","label":"datetime_fmt","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Compliance
  Batch Percentage","optionName":"metric_3th1a5tream_7nxhps9ndw","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=0 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Non-Compliance
  percentage","optionName":"metric_8j7gzz285iw_b2he8sreu1s","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=1 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Avg
  Batch Duration","optionName":"metric_4cxopcphn3s_ltamszkcaa","sqlExpression":"AVG(batch_duration)/60000"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Compliance
  Batch Percentage","optionName":"metric_3th1a5tream_7nxhps9ndw","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=0 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["datetime_fmt"],"columns":[],"aggregates":{"Compliance
  Batch Percentage":{"operator":"mean"},"Non-Compliance percentage":{"operator":"mean"},"Avg
  Batch Duration":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"4__table","viz_type":"echarts_timeseries_line","slice_id":15,"x_axis":"datetime_fmt","time_grain_sqla":"P1M","x_axis_sort_asc":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Compliance
  Batch Percentage","optionName":"metric_3th1a5tream_7nxhps9ndw","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=0 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Non-Compliance
  percentage","optionName":"metric_8j7gzz285iw_b2he8sreu1s","sqlExpression":"(SUM(\n        CASE\n            WHEN
  \n              batch_deviation_ind=1 \n            THEN 1\n            ELSE 0\n        END\n    )
  * 100.0 /(count (batch_no)))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Avg
  Batch Duration","optionName":"metric_4cxopcphn3s_ltamszkcaa","sqlExpression":"AVG(batch_duration)/60000"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_m4tordz3dgh_97adtsir75m","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"datetime_fmt"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title":"","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"seriesType":"line","only_total":true,"opacity":0.2,"markerEnabled":true,"markerSize":4,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"%b
  %Y","xAxisLabelRotation":90,"rich_tooltip":true,"showTooltipTotal":false,"showTooltipPercentage":false,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","currency_format":{},"truncateXAxis":false,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 93a61b86-61e8-4af4-b1b0-886fb8d8898d
version: 1.0.0
dataset_uuid: 7b9f14e2-e2fb-43df-a218-83c68f53c781
