slice_name: Wet Mix Time (YTD)
description: null
certified_by: null
certification_details: null
viz_type: histogram_v2
params:
  datasource: 3__table
  viz_type: histogram_v2
  slice_id: 16
  column: wet_mix_time
  min_column: wet_mix_time_spec_min
  max_column: wet_mix_time_spec_max
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: Last year
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_e82vvwq9zjf_1pwjz5qhwbyj
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: datetime_fmt
  row_limit: 10000
  bins: 5
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  show_legend: true
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"Last
  year"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["wet_mix_time"],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"histogram","options":{"column":"wet_mix_time","groupby":[],"bins":5}}]},{"filters":[{"col":"datetime_fmt","op":"TEMPORAL_RANGE","val":"Last
  year"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["wet_mix_time_spec_min","wet_mix_time_spec_max"],"annotation_layers":[],"row_limit":1,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"3__table","viz_type":"histogram_v2","slice_id":16,"column":"wet_mix_time","min_column":"wet_mix_time_spec_min","max_column":"wet_mix_time_spec_max","groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"Last
  year","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_e82vvwq9zjf_1pwjz5qhwbyj","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"datetime_fmt"}],"row_limit":10000,"bins":5,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"supersetColors","show_legend":true,"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fef90b59-2884-4bd7-a717-dc8f3cbcbd8b
version: 1.0.0
dataset_uuid: 7b9f14e2-e2fb-43df-a218-83c68f53c781
