table_name: Line Wise Ok and Not Ok Parameters
main_dttm_col: datetime_fmt
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: postgres
schema: public
sql: " SELECT \r\n    'Not Ok Mixes' AS category,\r\n    SUM(\r\n            CASE\
  \ WHEN batch_deviation_ind = 1 THEN 1 ELSE 0 END\r\n            \r\n        ) AS\
  \ value,\r\n    CASE \r\n        WHEN source_table_name = 'ABD1_Mixer_1' THEN 'Line1'\r\
  \n        WHEN source_table_name = 'ABD1_Mixer_2' THEN 'Line2'\r\n        WHEN source_table_name\
  \ = 'ABD1_Mixer_3' THEN 'Line3'\r\n        ELSE source_table_name  -- Ensures non-matching\
  \ values are retained\r\n    END AS line_name,\r\n    quarter,\r\n    source_table_name,\r\
  \n    battery_name,\r\n    datetime_fmt,\r\n    batch_no\r\nFROM \r\n    abd1_mixers_all\r\
  \n    WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n  GROUP\
  \ BY quarter,source_table_name,battery_name,datetime_fmt,batch_no\r\n\r\n  UNION\
  \ ALL\r\n\r\nSELECT \r\n    'Ok Mixes' AS category,\r\n    SUM(\r\n            CASE\
  \ WHEN batch_deviation_ind = 0 THEN 1 ELSE 0 END \r\n        ) AS value,\r\n   \
  \ CASE \r\n        WHEN source_table_name = 'ABD1_Mixer_1' THEN 'Line1'\r\n    \
  \    WHEN source_table_name = 'ABD1_Mixer_2' THEN 'Line2'\r\n        WHEN source_table_name\
  \ = 'ABD1_Mixer_3' THEN 'Line3'\r\n        ELSE source_table_name  -- Ensures non-matching\
  \ values are retained\r\n    END AS line_name,\r\n    quarter,\r\n    source_table_name,\r\
  \n    battery_name,\r\n    datetime_fmt,\r\n    batch_no\r\n    \r\nFROM \r\n  \
  \  abd1_mixers_all\r\n  WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt\
  \ > '{{ from_dttm }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n\
  \            datetime_fmt < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n     \
  \   1 = 1\r\n    )\r\n  GROUP BY quarter,source_table_name,battery_name,datetime_fmt,batch_no\r\
  \n  \r\n  UNION ALL\r\n\r\n  SELECT \r\n    'Total Mixes' AS category,\r\n    count(\r\
  \n           batch_no \r\n        ) AS value,\r\n    CASE \r\n        WHEN source_table_name\
  \ = 'ABD1_Mixer_1' THEN 'Line1'\r\n        WHEN source_table_name = 'ABD1_Mixer_2'\
  \ THEN 'Line2'\r\n        WHEN source_table_name = 'ABD1_Mixer_3' THEN 'Line3'\r\
  \n        ELSE source_table_name  -- Ensures non-matching values are retained\r\n\
  \    END AS line_name,\r\n    quarter,\r\n    source_table_name,\r\n    battery_name,\r\
  \n    datetime_fmt,\r\n    batch_no\r\n    \r\nFROM \r\n    abd1_mixers_all\r\n\
  \  WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n  GROUP\
  \ BY quarter,source_table_name,battery_name,datetime_fmt,batch_no\r\n    \r\n\r\n\
  \    \r\n"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 28d8b976-aef2-432b-a804-7859e18413a4
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: datetime_fmt
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: value
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: source_table_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: battery_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: batch_no
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: line_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: category
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: quarter
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
version: 1.0.0
database_uuid: 639ad6ad-9253-46ba-ac67-04355896a05c
