table_name: Overall Compliance
main_dttm_col: datetime_fmt
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: postgres
schema: public
sql: " SELECT \r\n    'Non-Compliance Batches' AS category,\r\n    SUM(\r\n      \
  \      CASE WHEN batch_deviation_ind = 1 THEN 1 ELSE 0 END\r\n            \r\n \
  \       ) AS value,\r\n    quarter,\r\n    source_table_name,\r\n    battery_name,\r\
  \n    datetime_fmt\r\nFROM \r\n    abd1_mixers_all\r\n    WHERE (\r\n        {%\
  \ if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n      \
  \  {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt < '{{ to_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n  GROUP BY quarter,source_table_name,battery_name,datetime_fmt\r\
  \n\r\nUNION ALL\r\n\r\nSELECT \r\n    'Compliance Batches' AS category,\r\n    SUM(\r\
  \n            CASE WHEN batch_deviation_ind = 0 THEN 1 ELSE 0 END \r\n        )\
  \ AS value,\r\n    quarter,\r\n    source_table_name,\r\n    battery_name,\r\n \
  \   datetime_fmt\r\n    \r\nFROM \r\n    abd1_mixers_all\r\n  WHERE (\r\n      \
  \  {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}' AND\r\n  \
  \      {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt < '{{\
  \ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n  GROUP BY\
  \ quarter,source_table_name,battery_name,datetime_fmt\r\n    \r\n"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: bac9c30e-364b-4e9b-9677-cb74f7a28936
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: datetime_fmt
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: {}
- column_name: value
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONGINTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: {}
- column_name: battery_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: {}
- column_name: category
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  extra: {}
- column_name: source_table_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: quarter
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: 639ad6ad-9253-46ba-ac67-04355896a05c
