table_name: Specification Compliance
main_dttm_col: datetime_fmt
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: postgres
schema: public
sql: "\r\n\r\n    SELECT \r\n        'Water Dumping Time (Sec)' AS category,\r\n \
  \       water_dump_time AS category_value,\r\n        CASE WHEN water_dump_time_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN water_dump_time_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n        \r\n    FROM abd1_mixers_all\r\
  \n    WHERE (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm\
  \ }}' AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \r\n    UNION ALL\r\n\r\n    SELECT \r\n        'Acid Dump Time (Sec)' AS category,\r\
  \n        acid_dump_time AS category_value,\r\n        CASE WHEN acid_dump_time_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN acid_dump_time_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Air Cooling Temp' AS category,\r\n\
  \        air_cooling_temp AS category_value,\r\n        CASE WHEN air_cooling_temp_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN air_cooling_temp_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Penetration of Paste' AS category,\r\
  \n        pentration AS category_value,\r\n        CASE WHEN pentration_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN pentration_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \r\n    UNION ALL\r\n\r\n    SELECT \r\n        'Density of Paste' AS category,\r\
  \n        density AS category_value,\r\n        CASE WHEN density_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN density_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n  \r\n    SELECT \r\n        'Acid Consumed' AS category,\r\n\
  \        acid_addition AS category_value,\r\n        CASE WHEN acid_addition_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN acid_addition_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n  \r\
  \n\r\n    UNION ALL\r\n\r\n    SELECT \r\n        'DM Water' AS category,\r\n  \
  \      dm_water AS category_value,\r\n        CASE WHEN dm_water_deviation_ind =\
  \ 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN dm_water_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n\r\n    SELECT \r\n        'Lead Oxide Consumed' AS category,\r\
  \n        lead_oxide AS category_value,\r\n        CASE WHEN lead_oxide_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN lead_oxide_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n   \
  \ \r\n\r\n    UNION ALL\r\n\r\n    SELECT \r\n        'Mixer Dump Temp' AS category,\r\
  \n        dump_temp AS category_value,\r\n        CASE WHEN dump_temp_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN dump_temp_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Highest Mixer Temp' AS category,\r\
  \n        peak_temp AS category_value,\r\n        CASE WHEN peak_temp_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN peak_temp_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Water Cooling In Temp' AS category,\r\
  \n        water_cooling_temp_in AS category_value,\r\n        CASE WHEN water_cooling_temp_in_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN water_cooling_temp_in_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n    \r\n    SELECT \r\n        'Final Water' AS category,\r\n\
  \        final_water AS category_value,\r\n        CASE WHEN trim_water_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN trim_water_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n    \r\n    SELECT \r\n        'Cooling On Temp' AS category,\r\
  \n        cooling_on_temp AS category_value,\r\n        CASE WHEN cooling_on_temp_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN cooling_on_temp_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Dry Mix Time (Sec)' AS category,\r\
  \n        dry_mix_time AS category_value,\r\n        CASE WHEN dry_mix_time_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN dry_mix_time_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )\r\n\r\n\
  \    UNION ALL\r\n\r\n    SELECT \r\n        'Wet Mix Time (Sec)' AS category,\r\
  \n        wet_mix_time AS category_value,\r\n        CASE WHEN wet_mix_time_deviation_ind\
  \ = 1 THEN 1 ELSE 0 END AS non_compliance,\r\n        CASE WHEN wet_mix_time_deviation_ind\
  \ = 0 THEN 1 ELSE 0 END AS compliance,\r\n        datetime_fmt,\r\n        source_table_name,\r\
  \n        battery_name,\r\n        shift\r\n    FROM abd1_mixers_all\r\n     WHERE\
  \ (\r\n        {% if from_dttm %}\r\n            datetime_fmt > '{{ from_dttm }}'\
  \ AND\r\n        {% endif %}\r\n        {% if to_dttm %}\r\n            datetime_fmt\
  \ < '{{ to_dttm }}' AND\r\n        {% endif %}\r\n        1 = 1\r\n    )"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: d4e3fcf1-dd88-422d-8375-60126a08894e
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: datetime_fmt
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: category_value
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: non_compliance
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: compliance
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: source_table_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: battery_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: category
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: 18417687-d619-42fe-a78b-7c26e1212281
